# file: roles/wetty/handlers/main.yml
---
# For example,
# 
- name: wetty
  service: name=wetty state=restarted

- name: reload systemd
  systemd: daemon_reload=yes

- name: sshd
  service: name=sshd state=restarted